name: Backend Cloud Run Deployment

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
  pull_request:
    paths:
      - "backend/**"

jobs:
  setup:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Google Cloud Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Setup Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"

      - name: Configure Docker
        run: gcloud artifacts repositories list --project=${{ vars.GCP_PROJECT_ID }}

  build-and-push:
    needs: setup
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Google Cloud Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"
          project_id: ${{ vars.GCP_PROJECT_ID }}
      - name: Setup Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"

      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev
      - name: list items
        run: gcloud container images list --repository=gcr.io/second-brain

  deploy:
    needs: Build-and-push
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy second-brain-backend \
              --image us-central1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GCR_REPO_NAME }}/backend:latest
              --platform managed \
              --port=8080 \
              --region us-central1 \
              --allow-unauthenticated \
              --set-env-vars PORT=8080
